### ISSUE TITLE
.build_release/lib/libcaffe.so: undefined reference to `boost::python::throw_error_already_set()'

### ISSUE THREAD

**Issue by monajalal** [rbgirshick/py-faster-rcnn#309]
```
I get this error with Python2.7 and Ubuntu15.10:

jalal@klein:~/computer_vision/py-faster-rcnn/caffe-fast-rcnn$ make -j8 && make pycaffe

CXX/LD -o .build_release/tools/compute_image_mean.bin
CXX/LD -o .build_release/tools/upgrade_net_proto_binary.bin
CXX/LD -o .build_release/tools/convert_imageset.bin
CXX/LD -o .build_release/tools/upgrade_net_proto_text.bin
CXX/LD -o .build_release/tools/caffe.bin
CXX/LD -o .build_release/tools/extract_features.bin
CXX/LD -o .build_release/tools/upgrade_solver_proto_text.bin
CXX/LD -o .build_release/examples/cpp_classification/classification.bin
/usr/bin/ld: warning: libboost_system.so.1.58.0, needed by .build_release/lib/libcaffe.so, may conflict with libboost_system.so.1.61.0
/usr/bin/ld: warning: libboost_thread.so.1.58.0, needed by .build_release/lib/libcaffe.so, may conflict with libboost_thread.so.1.61.0
.build_release/lib/libcaffe.so: undefined reference to `boost::python::throw_error_already_set()'
.build_release/lib/libcaffe.so: undefined reference to `boost::python::import(boost::python::str)'
.build_release/lib/libcaffe.so: undefined reference to `PyEval_CallFunction'
.build_release/lib/libcaffe.so: undefined reference to `typeinfo for boost::python::error_already_set'
.build_release/lib/libcaffe.so: undefined reference to `PyErr_Print'

```

How can I fix this?
I have boost installed.

**Comment by danielmorozoff** [comment]
I am seeing the same error. 

Trying to compile on Python 2.7.12 and Ubuntu 16.04
boost was installed via apt-get and then tried installing (successfully) from source

Did you have any luck with this?
